import { Blog, Tutorial, File, Service, Blogger, Category } from '@/types'

export const popularBlogs: Blog[] = [
  {
    id: 1,
    title: '重启web2.0博客时代的思考',
    author: '张三',
    date: '2026-02-19',
    views: 1234,
  },
  {
    id: 2,
    title: '如何构建个人知识管理系统',
    author: '李四',
    date: '2026-02-18',
    views: 987,
  },
  {
    id: 3,
    title: 'AI时代的内容创作趋势',
    author: '王五',
    date: '2026-02-17',
    views: 2345,
  },
  {
    id: 4,
    title: '个人品牌建设的重要性',
    author: '赵六',
    date: '2026-02-16',
    views: 1876,
  },
  {
    id: 5,
    title: '如何提高写作效率',
    author: '孙七',
    date: '2026-02-15',
    views: 1543,
  },
  {
    id: 6,
    title: 'Web3.0对个人创作者的影响',
    author: '周八',
    date: '2026-02-14',
    views: 2109,
  },
  {
    id: 7,
    title: '数据可视化工具推荐',
    author: '吴九',
    date: '2026-02-13',
    views: 1345,
  },
  {
    id: 8,
    title: '远程工作的最佳实践',
    author: '郑十',
    date: '2026-02-12',
    views: 1765,
  },
  {
    id: 9,
    title: '学习方法的革命',
    author: '王十一',
    date: '2026-02-11',
    views: 1987,
  },
  {
    id: 10,
    title: '如何打造个人IP',
    author: '赵十二',
    date: '2026-02-10',
    views: 2456,
  },
  {
    id: 11,
    title: '前端开发的未来趋势',
    author: '张三',
    date: '2026-02-09',
    views: 1678,
  },
  {
    id: 12,
    title: '后端架构设计原则',
    author: '李四',
    date: '2026-02-08',
    views: 1456,
  },
  {
    id: 13,
    title: '移动应用开发的挑战与机遇',
    author: '王五',
    date: '2026-02-07',
    views: 1987,
  },
  {
    id: 14,
    title: 'DevOps实践指南',
    author: '赵六',
    date: '2026-02-06',
    views: 1765,
  },
  {
    id: 15,
    title: '机器学习入门教程',
    author: '孙七',
    date: '2026-02-05',
    views: 2345,
  },
  {
    id: 16,
    title: 'UI/UX设计趋势',
    author: '周八',
    date: '2026-02-04',
    views: 1543,
  },
  {
    id: 17,
    title: '区块链技术应用场景',
    author: '吴九',
    date: '2026-02-03',
    views: 1876,
  },
  {
    id: 18,
    title: '云计算技术解析',
    author: '郑十',
    date: '2026-02-02',
    views: 1654,
  },
  {
    id: 19,
    title: '大数据处理技术',
    author: '王十一',
    date: '2026-02-01',
    views: 1789,
  },
  {
    id: 20,
    title: '人工智能伦理问题',
    author: '赵十二',
    date: '2026-01-31',
    views: 2134,
  },
]

export const popularTutorials: Tutorial[] = [
  {
    id: 1,
    title: 'React从入门到精通',
    author: '赵六',
    lessons: 24,
    students: 5678,
    excerpt: '本教程从React基础开始，逐步深入到高级特性，包括Hooks、Context API、Redux等，帮助你全面掌握React开发技能。',
  },
  {
    id: 2,
    title: 'Python数据分析实战',
    author: '孙七',
    lessons: 30,
    students: 4321,
    excerpt: '通过实际项目案例，学习Python数据分析的核心库和技术，包括NumPy、Pandas、Matplotlib等，提升你的数据分析能力。',
  },
  {
    id: 3,
    title: 'UI/UX设计原理',
    author: '周八',
    lessons: 18,
    students: 3456,
    excerpt: '了解UI/UX设计的基本原理和最佳实践，学习用户研究、原型设计、交互设计等技能，打造优秀的用户体验。',
  },
  {
    id: 4,
    title: 'Node.js后端开发',
    author: '吴九',
    lessons: 26,
    students: 2890,
    excerpt: '学习Node.js核心概念和Express框架，构建RESTful API和全栈应用，掌握后端开发技能。',
  },
  {
    id: 5,
    title: '机器学习入门',
    author: '郑十',
    lessons: 32,
    students: 4123,
    excerpt: '从基础概念开始，学习机器学习的核心算法和应用，通过实际项目掌握机器学习技能。',
  },
  {
    id: 6,
    title: 'Docker容器化技术',
    author: '王十一',
    lessons: 16,
    students: 2567,
    excerpt: '学习Docker的基本原理和使用方法，掌握容器化部署和微服务架构，提升开发和部署效率。',
  },
  {
    id: 7,
    title: 'Vue.js实战教程',
    author: '张三',
    lessons: 22,
    students: 3890,
    excerpt: '从Vue.js基础到高级应用，学习组件化开发、状态管理、路由等核心概念，构建现代化前端应用。',
  },
  {
    id: 8,
    title: 'Java后端开发',
    author: '李四',
    lessons: 35,
    students: 3245,
    excerpt: '学习Java核心技术、Spring Boot框架、数据库操作等，构建企业级后端应用。',
  },
  {
    id: 9,
    title: 'iOS应用开发',
    author: '王五',
    lessons: 28,
    students: 2789,
    excerpt: '学习Swift语言、iOS SDK、UIKit等，开发高质量的iOS应用。',
  },
  {
    id: 10,
    title: 'Android应用开发',
    author: '赵六',
    lessons: 30,
    students: 3123,
    excerpt: '学习Kotlin语言、Android SDK、Jetpack组件等，开发现代化的Android应用。',
  },
  {
    id: 11,
    title: 'TypeScript实战',
    author: '孙七',
    lessons: 20,
    students: 2987,
    excerpt: '学习TypeScript核心概念、类型系统、高级特性等，提升JavaScript代码的可维护性。',
  },
  {
    id: 12,
    title: 'GraphQL API设计',
    author: '周八',
    lessons: 18,
    students: 2654,
    excerpt: '学习GraphQL的基本原理、Schema设计、查询优化等，构建高效的API。',
  },
  {
    id: 13,
    title: '微服务架构实战',
    author: '吴九',
    lessons: 24,
    students: 3456,
    excerpt: '学习微服务架构的设计原则、服务发现、负载均衡、容错等核心概念。',
  },
  {
    id: 14,
    title: '数据结构与算法',
    author: '郑十',
    lessons: 40,
    students: 4567,
    excerpt: '学习常见的数据结构和算法，提升编程能力和解决问题的能力。',
  },
  {
    id: 15,
    title: 'DevOps实践',
    author: '王十一',
    lessons: 22,
    students: 3210,
    excerpt: '学习CI/CD、自动化测试、监控等DevOps核心实践，提升开发和部署效率。',
  },
]

export const popularFiles: File[] = [
  {
    id: 1,
    title: '前端开发面试题汇总',
    author: '张三',
    size: '2.5MB',
    downloads: 1234,
    excerpt: '包含HTML、CSS、JavaScript、React等前端技术的面试题和答案汇总。',
  },
  {
    id: 2,
    title: 'Python数据分析实战代码',
    author: '李四',
    size: '5.8MB',
    downloads: 987,
    excerpt: '《Python数据分析实战》一书的配套代码，包含所有章节的示例代码。',
  },
  {
    id: 3,
    title: 'UI设计资源包',
    author: '王五',
    size: '15.2MB',
    downloads: 2345,
    excerpt: '包含图标、字体、色彩方案等UI设计常用资源，适合设计师使用。',
  },
  {
    id: 4,
    title: '后端架构设计文档模板',
    author: '赵六',
    size: '1.2MB',
    downloads: 765,
    excerpt: '后端系统架构设计文档的模板，包含所有必要的章节和内容。',
  },
  {
    id: 5,
    title: 'Java核心技术笔记',
    author: '孙七',
    size: '3.5MB',
    downloads: 1123,
    excerpt: 'Java核心技术的详细笔记，包含语法、面向对象、集合框架等内容。',
  },
  {
    id: 6,
    title: 'React组件库',
    author: '周八',
    size: '8.7MB',
    downloads: 1567,
    excerpt: '常用的React组件库，包含按钮、表单、模态框等UI组件。',
  },
  {
    id: 7,
    title: '数据库设计最佳实践',
    author: '吴九',
    size: '2.1MB',
    downloads: 987,
    excerpt: '数据库设计的最佳实践指南，包含范式、索引、优化等内容。',
  },
  {
    id: 8,
    title: '前端性能优化指南',
    author: '郑十',
    size: '1.8MB',
    downloads: 1345,
    excerpt: '前端性能优化的详细指南，包含加载优化、渲染优化、资源优化等内容。',
  },
  {
    id: 9,
    title: '移动端UI设计规范',
    author: '王十一',
    size: '4.2MB',
    downloads: 1098,
    excerpt: '移动端UI设计的规范和最佳实践，包含iOS和Android平台的设计差异。',
  },
  {
    id: 10,
    title: 'API设计指南',
    author: '赵十二',
    size: '1.5MB',
    downloads: 876,
    excerpt: 'RESTful API设计的指南，包含命名规范、参数设计、错误处理等内容。',
  },
  {
    id: 11,
    title: 'Git命令速查手册',
    author: '张三',
    size: '0.8MB',
    downloads: 1678,
    excerpt: 'Git常用命令的速查手册，包含分支管理、提交、合并等操作。',
  },
  {
    id: 12,
    title: 'Linux命令行教程',
    author: '李四',
    size: '2.3MB',
    downloads: 1234,
    excerpt: 'Linux命令行的详细教程，包含文件操作、系统管理、网络配置等内容。',
  },
  {
    id: 13,
    title: '机器学习算法实现',
    author: '王五',
    size: '6.5MB',
    downloads: 1456,
    excerpt: '常见机器学习算法的Python实现，包含线性回归、决策树、神经网络等。',
  },
  {
    id: 14,
    title: '微服务架构设计文档',
    author: '赵六',
    size: '2.7MB',
    downloads: 987,
    excerpt: '微服务架构的设计文档模板，包含服务拆分、通信、部署等内容。',
  },
  {
    id: 15,
    title: '前端安全指南',
    author: '孙七',
    size: '1.9MB',
    downloads: 1123,
    excerpt: '前端安全的详细指南，包含XSS、CSRF、CSP等安全问题的防护措施。',
  },
]

export const qualityServices: Service[] = [
  {
    id: 1,
    title: '技术咨询',
    provider: '张三',
    price: '¥200/小时',
    rating: 4.9,
    excerpt: '提供前端、后端、移动端等技术领域的专业咨询服务。',
  },
  {
    id: 2,
    title: '代码审查',
    provider: '李四',
    price: '¥300/次',
    rating: 4.8,
    excerpt: '专业的代码审查服务，帮助你发现并修复代码中的问题。',
  },
  {
    id: 3,
    title: '技术培训',
    provider: '王五',
    price: '¥1500/天',
    rating: 4.7,
    excerpt: '提供企业级技术培训，包括前端、后端、DevOps等领域。',
  },
  {
    id: 4,
    title: '项目外包',
    provider: '赵六',
    price: '面议',
    rating: 4.9,
    excerpt: '承接各类软件开发项目，包括Web应用、移动应用等。',
  },
  {
    id: 5,
    title: 'UI/UX设计',
    provider: '孙七',
    price: '¥1000/页',
    rating: 4.8,
    excerpt: '提供专业的UI/UX设计服务，包括产品设计、界面设计、用户体验设计等。',
  },
  {
    id: 6,
    title: '数据库设计',
    provider: '周八',
    price: '¥500/次',
    rating: 4.7,
    excerpt: '提供数据库设计服务，包括概念设计、逻辑设计、物理设计等。',
  },
  {
    id: 7,
    title: 'API开发',
    provider: '吴九',
    price: '¥800/接口',
    rating: 4.9,
    excerpt: '提供RESTful API、GraphQL API等接口开发服务。',
  },
  {
    id: 8,
    title: '性能优化',
    provider: '郑十',
    price: '¥1500/次',
    rating: 4.8,
    excerpt: '提供系统性能优化服务，包括前端性能优化、后端性能优化、数据库优化等。',
  },
  {
    id: 9,
    title: '安全审计',
    provider: '王十一',
    price: '¥2000/次',
    rating: 4.9,
    excerpt: '提供系统安全审计服务，包括代码安全审计、架构安全审计、渗透测试等。',
  },
  {
    id: 10,
    title: 'DevOps实施',
    provider: '赵十二',
    price: '¥3000/次',
    rating: 4.7,
    excerpt: '提供DevOps实施服务，包括CI/CD流程搭建、自动化测试、监控系统搭建等。',
  },
  {
    id: 11,
    title: '移动应用开发',
    provider: '张三',
    price: '¥5000/款',
    rating: 4.8,
    excerpt: '提供iOS、Android等移动应用开发服务。',
  },
  {
    id: 12,
    title: 'Web应用开发',
    provider: '李四',
    price: '¥8000/款',
    rating: 4.9,
    excerpt: '提供响应式Web应用开发服务，包括前端、后端、数据库等。',
  },
  {
    id: 13,
    title: '数据分析',
    provider: '王五',
    price: '¥300/小时',
    rating: 4.7,
    excerpt: '提供数据分析服务，包括数据采集、数据清洗、数据分析、数据可视化等。',
  },
  {
    id: 14,
    title: '机器学习模型开发',
    provider: '赵六',
    price: '¥5000/模型',
    rating: 4.8,
    excerpt: '提供机器学习模型开发服务，包括数据预处理、特征工程、模型训练、模型部署等。',
  },
  {
    id: 15,
    title: '技术文档编写',
    provider: '孙七',
    price: '¥200/页',
    rating: 4.6,
    excerpt: '提供技术文档编写服务，包括需求文档、设计文档、用户手册等。',
  },
]

export const smartBloggers: Blogger[] = [
  {
    id: 1,
    name: '张三',
    avatar: '👨‍💻',
    followers: 12345,
    articles: 128,
    description: '前端技术专家，专注于React、Vue等前端框架的研究和分享。',
  },
  {
    id: 2,
    name: '李四',
    avatar: '👩‍💻',
    followers: 9876,
    articles: 96,
    description: '数据科学家，专注于机器学习、数据分析等领域的技术分享。',
  },
  {
    id: 3,
    name: '王五',
    avatar: '👨‍🎨',
    followers: 7654,
    articles: 85,
    description: 'UI/UX设计师，分享设计理念、工具使用技巧等内容。',
  },
  {
    id: 4,
    name: '赵六',
    avatar: '👩‍🚀',
    followers: 15432,
    articles: 156,
    description: '全栈开发者，分享后端、前端、DevOps等全栈技术内容。',
  },
  {
    id: 5,
    name: '孙七',
    avatar: '👨‍🔬',
    followers: 8765,
    articles: 78,
    description: '人工智能专家，专注于机器学习、深度学习等领域的研究和分享。',
  },
  {
    id: 6,
    name: '周八',
    avatar: '👩‍💼',
    followers: 11234,
    articles: 102,
    description: '产品经理，分享产品设计、用户研究、项目管理等内容。',
  },
  {
    id: 7,
    name: '吴九',
    avatar: '👨‍🏫',
    followers: 9876,
    articles: 115,
    description: '技术讲师，专注于编程教育、技术培训等内容的分享。',
  },
  {
    id: 8,
    name: '郑十',
    avatar: '👩‍🎓',
    followers: 7654,
    articles: 89,
    description: '计算机科学博士，分享算法、数据结构、系统设计等内容。',
  },
  {
    id: 9,
    name: '王十一',
    avatar: '👨‍💾',
    followers: 10987,
    articles: 95,
    description: '后端开发者，专注于Java、Spring Boot、微服务等后端技术的分享。',
  },
  {
    id: 10,
    name: '赵十二',
    avatar: '👩‍🎮',
    followers: 8765,
    articles: 76,
    description: '游戏开发者，分享游戏设计、Unity、Unreal Engine等游戏开发技术。',
  },
  {
    id: 11,
    name: '钱十三',
    avatar: '👨‍🚒',
    followers: 12345,
    articles: 134,
    description: 'DevOps工程师，分享CI/CD、容器化、自动化运维等内容。',
  },
  {
    id: 12,
    name: '孙十四',
    avatar: '👩‍⚕️',
    followers: 9876,
    articles: 87,
    description: '医疗科技专家，分享医疗信息化、健康科技等内容。',
  },
  {
    id: 13,
    name: '周十五',
    avatar: '👨‍🎤',
    followers: 7654,
    articles: 65,
    description: '音乐科技专家，分享音乐制作、音频处理等内容。',
  },
  {
    id: 14,
    name: '吴十六',
    avatar: '👩‍🌾',
    followers: 8765,
    articles: 72,
    description: '农业科技专家，分享智慧农业、农业信息化等内容。',
  },
  {
    id: 15,
    name: '郑十七',
    avatar: '👨‍🚀',
    followers: 10987,
    articles: 98,
    description: '航天科技专家，分享航天技术、卫星应用等内容。',
  },
]

export const blogCategories: Category[] = [
  { id: 1, name: '前端开发', count: 1234 },
  { id: 2, name: '后端开发', count: 987 },
  { id: 3, name: '移动开发', count: 765 },
  { id: 4, name: '人工智能', count: 876 },
  { id: 5, name: '数据分析', count: 654 },
  { id: 6, name: 'DevOps', count: 543 },
  { id: 7, name: 'UI/UX设计', count: 432 },
  { id: 8, name: '产品经理', count: 321 },
]

export const tutorialCategories: Category[] = [
  { id: 1, name: '前端开发', count: 567 },
  { id: 2, name: '后端开发', count: 432 },
  { id: 3, name: '移动开发', count: 345 },
  { id: 4, name: '人工智能', count: 456 },
  { id: 5, name: '数据分析', count: 234 },
  { id: 6, name: 'DevOps', count: 123 },
  { id: 7, name: 'UI/UX设计', count: 189 },
  { id: 8, name: '产品经理', count: 98 },
]

export const commonTags: string[] = [
  'React', 'Python', 'JavaScript', 'Java', 'TypeScript', 'Vue', 'Docker', 'Kubernetes',
  'AWS', 'Azure', 'GCP', '机器学习', '深度学习', '数据可视化', '前端架构',
]